import Head from "next/head";
import Image from "next/image";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import AnimatedLogo from "@/components/AnimatedLogo";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Minting Station</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col text-center  items-center">
        <AnimatedLogo />
        <h1 className="text-2xl uppercase font-semibold  mt-4">
          No code Toolkit for NFT CREATORS
        </h1>
        <p className="text-lg mx-auto my-4 max-w-2xl">
          Create your own AWESOME NFT’s in as little as 3 minutes and share your
          collection with the world !!!!
        </p>
        <Link href="/create">
          <button className="btn-primary">BEGIN</button>
        </Link>
      </main>
    </>
  );
}
